#!/bin/bash

$(cat ~/.FPkg/shell.var) ~/.FPkg/.fshrc

if [[ $(/bin/id -u) == 1000 ]]
then
	user=$
elif [[ $(/bin/id -u) == 10264 ]]
then
	user=$
elif [[ $(/bin/id -u) == 0 ]]
then
	user=#
fi

read -p "$user:" cmd

if [[ $cmd == clear-shell-history ]]
then
		echo "Clearing history..."
		rm -rf ~/.FPkg/shell-hist
		touch ~/.FPkg/shell-hist
		echo "Adding cancel option..."
		echo "Cancel" &>> ~/.FPkg/shell-hist
		dontexec=y
elif [[ $dontexec == "" ]]
then
echo $cmd &>> ~/.FPkg/shell-hist
$cmd
fi
$(cat ~/.FPkg/shell.var) ~/.FPkg/FSh
